### PR TITLE
Added HomePage.

### PR DESCRIPTION
**Pull request by vrinda-mahajan**
I have added the home page for the e-commerce app. Please review the PR.

Preview: https://jovial-bhabha-dcb5f3.netlify.app/

### CODE REVIEW

**Review by VLeads — APPROVED** [review]
Code looks good !

**Review by VLeads — APPROVED** [review]

**Comment by VLeads** [comment]
You have made an elegant design 💯.

**Review by foolhardy21 — APPROVED** [review]
LGTM. 👍🏾

**Review by BalajiHarinath — APPROVED** [review]
Looks good to me. Just change "Make you own garden at home" to -> "Make your* own garden at home"

**Comment by vrinda-mahajan** [comment]
> Looks good to me. Just change "Make you own garden at home" to -> "Make your* own garden at home"

Yeah. That's a typo. I will correct it.

**Comment by vrinda-mahajan** [comment]
> You have made an elegant design 💯.

Thank you.

**Pull request merged**
